#!/usr/bin/env bash

HOME="${HOME:-/home/ch}"
DOTFILES="${DOTFILES:-$HOME/projects/dotfiles}"
LOCAL_BIN="${LOCAL_BIN:-$HOME/.local/bin}"

function links {
  rm -rf \
    $HOME/.zshrc \
    $HOME/.vimrc \
    $HOME/.saml2aws \
    $HOME/.aws/config \
    $HOME/.config/nvim \
    $HOME/.config/git \
    $HOME/.config/ghostty \
    $HOME/.config/user-dirs.dirs \
    $HOME/.local/share/applications/zen.desktop \
    $HOME/.local/share/applications/ghostty.desktop \
    $HOME/.local/share/icons/ghostty.png \
    $HOME/.local/share/icons/zen.png \
    $HOME/.local/share/fonts

  ln -s $DOTFILES/.zshrc $HOME/.zshrc
  ln -s $DOTFILES/.vimrc $HOME/.vimrc
  ln -s $DOTFILES/.saml2aws $HOME/.saml2aws
  ln -s $DOTFILES/.aws/config $HOME/.aws/config
  ln -s $DOTFILES/.config/nvim $HOME/.config/nvim
  ln -s $DOTFILES/.config/git $HOME/.config/git
  ln -s $DOTFILES/.config/ghostty $HOME/.config/ghostty
  ln -s $DOTFILES/.config/user-dirs.dirs $HOME/.config/user-dirs.dirs
  ln -s $DOTFILES/.local/share/applications/zen.desktop $HOME/.local/share/applications/zen.desktop
  ln -s $DOTFILES/.local/share/applications/ghostty.desktop $HOME/.local/share/applications/ghostty.desktop
  ln -s $DOTFILES/.local/share/icons/ghostty.png $HOME/.local/share/icons/ghostty.png
  ln -s $DOTFILES/.local/share/icons/zen.png $HOME/.local/share/icons/zen.png
  ln -s $DOTFILES/.local/share/fonts $HOME/.local/share/fonts
}

function bin {
  # Neovim
  curl -fsSL https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.appimage -o $LOCAL_BIN/nvim \
    && chmod +x $LOCAL_BIN/nvim

  # Zoxide
  curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

  # Zen
  curl -fsSL https://github.com/zen-browser/desktop/releases/latest/download/zen-x86_64.AppImage -o $LOCAL_BIN/zen \
    && chmod +x $LOCAL_BIN/zen

  # Ghostty
  curl -fsSL https://github.com/psadi/ghostty-appimage/releases/download/v1.1.2%2B4/Ghostty-1.1.2-x86_64.AppImage -o $LOCAL_BIN/ghostty \
    && chmod +x $LOCAL_BIN/ghostty

  # Direnv
  curl -fsSL https://direnv.net/install.sh | bash

  # Docker
  curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh

  # Just
  curl --proto '=https' --tlsv1.2 -fsSL https://just.systems/install.sh | bash -s -- --to $LOCAL_BIN

  # Atuin
  curl --proto '=https' --tlsv1.2 -fsSL https://setup.atuin.sh | sh

  # Rustup
  curl --proto '=https' --tlsv1.2 -fsSL https://sh.rustup.rs | sh

  # Saml2aws
  CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1) \
    && curl -fsSL "https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz" \
      | tar -xz -C $LOCAL_BIN \
    && chmod +x $LOCAL_BIN/saml2aws

  # AWS CLI
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && sudo ./aws/install --bin-dir $LOCAL_BIN --install-dir $HOME/.local/aws-cli \
    && rm awscliv2.zip

  # Eza
  curl -fsSL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz \
    | tar -xz -C $LOCAL_BIN \
    && chmod +x $LOCAL_BIN/eza

  # Fd
  curl -fsSL https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-gnu.tar.gz \
    | tar -xz -C $LOCAL_BIN \
    && chmod +x $LOCAL_BIN/fd

  # Ripgrep
  curl -fsSL https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz \
    | tar -xz -C $LOCAL_BIN \
    && chmod +x $LOCAL_BIN/rg

  # Nala
  curl -fsSL https://gitlab.com/-/project/31927362/uploads/1164b1c240e4cdacc652b3dd5953c3d1/nala_0.15.4_all.deb -O nala.deb \
    && sudo dpkg -i nala.deb \
    && rm nala.deb

  # Volta
  curl https://get.volta.sh | bash

  # Pnpm
  curl -fsSL https://get.pnpm.io/install.sh | sh -
}

"$@"
