[theme]
name = "nord"

[colors]
AlertInfo = "#a3be8c"
AlertWarn = "#d08770"
AlertError = "#bf616a"
Annotation = "#4c566a"
Base = "#e5e9f0"
Guidance = "#4c566a"
Important = "#81a1c1"
Title = "#88c0d0"
