[git_branch]
symbol = ""

[package]
symbol = ""

[aws]
symbol = ""

[rust]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[custom.rv]
command = "rv which" # shows output of command
style = "bold green"
format = "with [$output]($style)"
when = ''' test -n "$(rv which)" '''
